apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fava.fullname" . }}
  labels:
    app: {{ template "fava.name" . }}
    chart: {{ template "fava.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fava.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fava.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FAVA_OPTIONS
              value: "-H 0.0.0.0 -p {{ .Values.service.port }}"
            - name: BEANCOUNT_INPUT_FILE
              value: "/data/{{ .Values.beancount }}"
            - name: PREFIX
              value: "{{ .Values.service.prefix }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {{ .Values.persistence.data.subPath }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (include "fava.fullname" .) }}
    {{- with .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
