# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: alexiri/bitcoind
  tag: 0.16.1
  pullPolicy: Always

service:
  rpcPort: 8332
  p2pPort: 8333
  p2pPortPublic: 30833
  testnetPort: 18332
  testnetP2pPort: 18333

persistence:
  enabled: true
  subPath: bitcoind
  existingClaim: shared-data

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 1Gi
    cpu: "0.1"

probes:
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 15
    successThreshold: 1
