# Default values for backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: alexiri/restic
  tag: 0.1
  pullPolicy: IfNotPresent

schedule:
  kube: "0 */4 * * *"
  nas: "@daily"
  cleanup: "0 23 * * *"

persistence:
  restic:
    subPath: restic
    existingClaim: shared-data
  kube:
    existingClaim: shared-data
  data:
    existingClaim: download-data
