# Default values for deluged.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always
  deluged:
    repository: alexiri/deluge-deluged
    tag: 0.2
  delugeweb:
    repository: alexiri/deluge-delugeweb
    tag: 0.1

service:
  rpcPort: 58846
  rpcPortPublic: 30846
  p2pPort: 58946
  p2pPortPublic: 30946
  webPort: 8112
  webPortPublic: 30811

persistence:
  config:
    subPath: deluge
    existingClaim: shared-data
  data:
    existingClaim: download-data

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  deluged:
    requests:
      memory: 1Gi
      cpu: 300m
  delugeweb:
    requests:
      memory: 50Mi
      cpu: 100m

probes:
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 15
    successThreshold: 1
