# Default values for deluged.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: alexiri/deluge-deluged
  tag: 0.2
  pullPolicy: IfNotPresent

service:
  rpcPort: 58846
  p2pPort: 58946

persistence:
  config:
    subPath: deluge
    existingClaim: shared-data
  data:
    existingClaim: download-data

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 300m

probes:
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 15
    successThreshold: 1
