
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx-proxy.fullname" . }}
  labels:
    app: {{ template "nginx-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  grafana.conf: |+
    location /grafana {
      rewrite /grafana/(.*) /$1 break;
      proxy_pass         http://grafana.iot:80/;
    }

    location /fava {
      auth_basic          "Private Area";
      auth_basic_user_file /etc/nginx/conf.d/htpasswd;
      proxy_pass         http://fava.beancount:80/;
      proxy_redirect     http://fava.beancount/    https://alexiri.duckdns.org:3000/fava/;
    }
  htpasswd: |+
    # Password list
    user:$apr1$qxqaT9tI$YEpkY2yG5ODqkAUvCohQX.
    #

