
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx-proxy.fullname" . }}
  labels:
    app: {{ template "nginx-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  grafana.conf: |+
    location /grafana {
      rewrite /grafana/(.*) /$1 break;
      proxy_pass         http://grafana.iot.svc.kube:80/;
    }
