apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "nginx-proxy.fullname" . }}
  labels:
    app: {{ template "nginx-proxy.name" . }}
    chart: {{ template "nginx-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print .Template.BasePath "/config.yaml") . | sha256sum }}
    use-proxy-protocol: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "nginx-proxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nginx-proxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: health
              containerPort: 8080
              protocol: TCP
          env:
            - name: WATCH_PATHS
              value: "/etc/nginx /certs"
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: certs
              mountPath: /certs
              subPath: {{ .Values.certs.subPath }}
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.resources | indent 12 }}
      # Load the configuration files for nginx
      volumes:
        - name: config
          configMap:
            name: {{ template "nginx-proxy.fullname" . }}
        - name: certs
          persistentVolumeClaim:
            claimName: {{ .Values.certs.existingClaim }}
