apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-proxy.fullname" . }}
  labels:
    app: {{ template "nginx-proxy.name" . }}
    chart: {{ template "nginx-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "nginx-proxy.name" . }}
    release: {{ .Release.Name }}
