name: influxdb
version: 0.10.0
appVersion: 1.5.4
description: Scalable datastore for metrics, events, and real-time analytics.
keywords:
  - influxdb
  - database
  - timeseries
home: https://www.influxdata.com/time-series-platform/influxdb/
icon: https://raw.githubusercontent.com/alexiri/helmcharts/master/influxdb/Influxdb-Logo.svg
sources:
  - https://github.com/influxdata/influxdb
maintainers:
  - name: jackzampolin
    email: jack@influxdb.com
engine: gotpl
