apiVersion: v1
kind: Service
metadata:
  name: {{ template "deluge.fullname" . }}
  labels:
    app: {{ template "deluge.name" . }}
    chart: {{ template "deluge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: rpc
      targetPort: rpc
      port: {{ .Values.service.rpcPort }}
      nodePort: {{ .Values.service.rpcPortPublic }}
    - name: p2p
      targetPort: p2p
      port: {{ .Values.service.p2pPort }}
      nodePort: {{ .Values.service.p2pPortPublic }}
    - name: p2p-udp
      targetPort: p2p
      port: {{ .Values.service.p2pPort }}
      nodePort: {{ .Values.service.p2pPortPublic }}
      protocol: UDP
    - name: web
      targetPort: web
      port: {{ .Values.service.webPort }}
      nodePort: {{ .Values.service.webPortPublic }}
  selector:
    app: {{ template "deluge.name" . }}
    release: {{ .Release.Name }}
