apiVersion: v1
kind: Service
metadata:
  name: {{ template "deluge.fullname" . }}
  labels:
    app: {{ template "deluge.name" . }}
    chart: {{ template "deluge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: p2p-udp
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: UDP
  selector:
    app: {{ template "deluge.name" . }}
    release: {{ .Release.Name }}
